# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2

jobs:

  deploy-beta:
    docker:
      - image: circleci/php:7.1-node-browsers
    working_directory: ~/support-beta
    steps:
      - checkout
      - run: pwd
      - run: sudo apt install rsync
      - add_ssh_keys:
          fingerprints:
              - "04:84:bc:6d:f4:2d:7c:dc:f8:26:1b:67:70:59:80:fb"
      - deploy:
          name: Deploy Over SSH
          command: >
            rsync -e "ssh -o StrictHostKeyChecking=no" -arvc \
              --exclude .git ~/support-beta/ \
              serveradmin%brooklynrail.org@s14056.gridserver.com:~/domains/brooklynrail.org/html/support-beta

  deploy-master:
    docker:
      - image: circleci/php:7.1-node-browsers
    working_directory: ~/donate
    steps:
      - checkout
      - run: pwd
      - run: sudo apt install rsync
      - deploy:
          name: Deploy Over SSH
          command: >
            rsync -e "ssh -o StrictHostKeyChecking=no" -arvc \
              --exclude .git ~/donate/ \
              serveradmin%s228460.gridserver.com@s228460.gridserver.com:~/domains/s228460.gridserver.com/html/

workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy-beta:
          filters:
            branches:
              only: beta
      - deploy-master:
          filters:
            branches:
              only: master
