# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    working_directory: ~/support
    steps:
      - checkout
      - run: composer install
      - deploy:
          name: Deploy Over SSH
          command: scp -r -o StrictHostKeyChecking=no ~/support serveradmin%brooklynrail.org@brooklynrail.org:~/domains/circleci.brooklynrail.org/html/support
