# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2

jobs:

  deploy-beta:
    docker:
      - image: circleci/php:7.1-node-browsers
    working_directory: ~/support-beta
    steps:
      - checkout
      - run: php composer.phar install
      - run: pwd
      - run: sudo apt install rsync
      - deploy:
          name: Deploy Over SSH
          command: >
            rsync -e "ssh -o StrictHostKeyChecking=no" -arvc \
              --exclude .git ~/support-beta/ \
              serveradmin%brooklynrail.org@brooklynrail.org:~/domains/brooklynrail.org/html/support-beta

  deploy-master:
    docker:
      - image: circleci/php:7.1-node-browsers
    working_directory: ~/donate
    steps:
      - checkout
      - run: php composer.phar install
      - run: pwd
      - deploy:
          name: Deploy Over SSH
          command: >
            rsync -e "ssh -o StrictHostKeyChecking=no" -arvc \
              --exclude .git ~/donate/ \
              serveradmin%brooklynrail.org@brooklynrail.org:~/domains/brooklynrail.org/html/donate

workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy-beta:
          filters:
            branches:
              only: beta
      - deploy-master:
          filters:
            branches:
              only: master
