# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2

jobs:
  beta-build:
    branches:
      only:
        - beta
    docker:
      - image: circleci/php:7.1-node-browsers
    working_directory: ~/support-beta
    steps:
      - checkout
      - run: php composer.phar install
      - run: pwd
      - deploy:
          name: Deploy Over SSH
          command: rsync -e "ssh -o StrictHostKeyChecking=no" -arvc --exclude .git ~/support-beta/ serveradmin%brooklynrail.org@brooklynrail.org:~/domains/brooklynrail.org/html/support-beta
  master-build:
    branches:
      only:
        - master
    docker:
      - image: circleci/php:7.1-node-browsers
    working_directory: ~/support
    steps:
      - checkout
      - run: php composer.phar install
      - run: pwd
      - deploy:
          name: Deploy Over SSH
          command: rsync -e "ssh -o StrictHostKeyChecking=no" -arvc --exclude .git ~/support/ serveradmin%brooklynrail.org@brooklynrail.org:~/domains/brooklynrail.org/html/support

workflows:
  version: 2
  build-deploy:
    jobs:
      - beta-build:
          filters:
            branches:
              only: beta
      - master-build:
          filters:
            branches:
              only: master
